version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd aws
      - mvn -v
      - mvn clean package -DskipTests

artifacts:
  files:
    - aws/target/*.jar